- conf/prod.routes
Application will run under /lifetime-isa (until decided otherwise)
> Updated base URL

- app/controllers/HomePage.scala
- app/controllers/Registration.scala
- app/views/govuk_wrapper.scala.html
- app/views/helloworld/hello_world.scala.html
- app/views/home/home.scala.html
- app/views/registration/organisationDetails.scala.html
- conf/app.routes
- test/controllers/HomePageControllerSpec.scala
- test/controllers/RegistrationControllerSpec.scala
Created the landing page for the service based on iteration 4 (latest available at the moment).
Added a blank first page for the registration process.
Linked the two together with an unauthenticated hyperlink.
> Landing page 409

- app/config/frontendWiring.scala
- app/controllers/Registration.scala
- app/views/govuk_wrapper.scala.html
- conf/application.conf
- project/FrontendBuild.scala
- project/MicroService.scala
- project/plugins.sbt
- test/controllers/RegistrationControllerSpec.scala
LISA-111
Added basic logic checking to the organisation details page.
Merely checks if the user is logged in or not, no eligability or authorisation checks.
Redirects to gov gateway for logging in passing a hard coded (for now) return url.
> Authentication Mechanism

- project/FrontendBuild.scala
> Updated frontend bootstrap version

- conf/application.conf
Previously was blocked by the Content Security Policy
> Updated application.conf to allow CONTACT_FRONTEND to work locally

- project/FrontendBuild.scala
As per update on Techspace Blog
> Updated version of Play UI to pass new Bobby rules

- app/views/home/home.scala.html
Updated as per latest prototype
> LISA-822: Amended landing page

- app/controllers/BusinessStructureController.scala
- app/controllers/OrganisationDetailsController.scala
- app/controllers/RosmController.scala
- app/models/OrganisationDetails.scala
- app/models/TradingDetails.scala
- app/views/home/home.scala.html
- app/views/registration/organisation_details.scala.html
- app/views/registration/summary.scala.html
- app/views/registration/trading_details.scala.html
- conf/app.routes
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/RosmControllerSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/controllers/TradingDetailsControllerSpec.scala
Updated as per user story.
Back link and testing still to do, but covered by separate tasks on the story.
> LISA-822: Amended organisation name & trading details pages

- app/config/frontendAppConfig.scala
- app/controllers/ApplicationSubmittedController.scala
- app/controllers/BusinessStructureController.scala
- app/controllers/ErrorController.scala
- app/controllers/LisaBaseController.scala
- app/controllers/OrganisationDetailsController.scala
- app/controllers/RosmController.scala
- app/controllers/SummaryController.scala
- app/controllers/TradingDetailsController.scala
- app/controllers/YourDetailsController.scala
- app/models/BusinessStructure.scala
- app/models/OrganisationDetails.scala
- app/models/TradingDetails.scala
- app/models/YourDetails.scala
- app/views/home/home.scala.html
- app/views/registration/application_submitted.scala.html
- conf/app.routes
- conf/application.conf
- test/controllers/ApplicationSubmittedControllerSpec.scala
- test/controllers/BusinessStructureControllerSpec.scala
- test/controllers/LisaBaseControllerSpec.scala
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/RosmControllerSpec.scala
Removed duplication around:
* Forms
* Cache IDs
* Checking all registration data is present
> LISA-822: Refactored controllers

- app/controllers/ApplicationSubmittedController.scala
- app/controllers/BusinessStructureController.scala
- app/controllers/ErrorController.scala
- app/controllers/LisaBaseController.scala
- app/controllers/OrganisationDetailsController.scala
- app/controllers/RosmController.scala
- app/controllers/SummaryController.scala
- app/controllers/TradingDetailsController.scala
- app/controllers/YourDetailsController.scala
- app/models/BusinessStructure.scala
- app/models/OrganisationDetails.scala
- app/models/TradingDetails.scala
- app/models/YourDetails.scala
- app/views/registration/summary.scala.html
- test/controllers/ApplicationSubmittedControllerSpec.scala
- test/controllers/BusinessStructureControllerSpec.scala
- test/controllers/LisaBaseControllerSpec.scala
Upon amending your answers you will be taken straight back to the 'check your answers' page, rather than stepping forward through the whole registration process.
> LISA-822: Amended check your answer workflow

- app/views/registration/summary.scala.html
Added to aid with acceptance testing
> LISA-822: Added numerous IDs to the summary page

- app/controllers/ApplicationSubmittedController.scala
- app/views/error_template.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/home/home.scala.html
- app/views/main_template.scala.html
- app/views/registration/application_pending.scala.html
- conf/app.routes
- test/controllers/ApplicationSubmittedControllerSpec.scala
Static page initially, further functionality to follow in future stories.
> LISA-827: Application pending page

- app/controllers/RosmController.scala
- app/services/RosmService.scala
- test/controllers/RosmControllerSpec.scala
- test/services/RosmServiceSpec.scala
* Amended controller to do a pattern match rather than checking res.isLeft
* Inverted logic on the Either so that Right is the success value and Left the error (as per popular convention)
> LISA-971: Amended ROSM code slightly

- app/controllers/ApplicationSubmittedController.scala
- app/controllers/BusinessStructureController.scala
- app/controllers/LisaBaseController.scala
- app/controllers/OrganisationDetailsController.scala
- app/controllers/RosmController.scala
- app/controllers/SummaryController.scala
- app/controllers/TradingDetailsController.scala
- app/controllers/YourDetailsController.scala
- app/models/UserDetails.scala
- app/services/AuthorisationService.scala
- test/connectors/RosmConnectorSpec.scala
- test/connectors/RosmJsonFormatsSpec.scala
- test/connectors/TaxEnrolmentConnectorSpec.scala
- test/connectors/TaxEnrolmentJsonFormatsSpec.scala
- test/connectors/UserDetailsConnectorSpec.scala
- test/controllers/ApplicationSubmittedControllerSpec.scala
- test/controllers/BusinessStructureControllerSpec.scala
- test/controllers/HomePageControllerSpec.scala
- test/controllers/LisaBaseControllerSpec.scala
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/RosmControllerSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/controllers/TradingDetailsControllerSpec.scala
- test/controllers/YourDetailsControllerSpec.scala
- test/services/AuthorisationServiceSpec.scala
Created a Authorisation service which the base controller now invokes.
> LISA-999: Decoupled auth from base controller

- app/views/registration/summary.scala.html
Has a little crossover with LISA-1009, but there's still further work for 1009 to come...
> LISA-1010: Updated section ordering on summary page

- app/connectors/TaxEnrolmentConnector.scala
- app/connectors/TaxEnrolmentJsonFormats.scala
- app/controllers/RosmController.scala
- app/models/TaxEnrolment.scala
- app/services/TaxEnrolmentService.scala
- test/connectors/TaxEnrolmentConnectorSpec.scala
- test/controllers/RosmControllerSpec.scala
- test/services/TaxEnrolmentServiceSpec.scala
Now handled entirely within the backend microservice as part of the ROSM subscribe call
> LISA-1020: Removed calls to Tax Enrolment subscribe endpoint

- app/views/govuk_wrapper.scala.html
- app/views/main_template.scala.html
- app/views/registration/application_submitted.scala.html
Should now track a virtual page view for application sent - thereby omitting email from the URL
> LISA-965: Updated GA tracking

- app/views/registration/application_submitted.scala.html
Setting location as well as page
> LISA-965: Amended GA tracking code

- app/controllers/ApplicationSubmittedController.scala
- app/controllers/LisaBaseController.scala
- test/controllers/ApplicationSubmittedControllerSpec.scala
Further work to follow to make the bypassing of the enrolment check conditional and to only apply on the initial submission.
> LISA-1057: Interim fix to ensure application sent page gets seen

- app/views/home/home.scala.html
Not ideal solution but has been cross browser tested
> Updated lisa homepage to remove margin from page title

- test/controllers/OrganisationDetailsControllerSpec.scala
The controller method was being called before mockito setup.
Formatted the code a little also while I was on.
> LISA-1101: Fixed failing Unit Test

- app/views/registration/matching_failed.scala.html
Voiceover reads LTD as "limited", making the sentence "You need to check that your business name uses either limited or limited". Aria label of L.T.D. makes it sound out as expected.
> LISA-1159: Accessibility fix

- app/views/govuk_wrapper.scala.html
- conf/app.routes
- project/MicroService.scala
- project/plugins.sbt
Added an asset pipeline to allow us to have SCSS files in our service.
> LISA-1296: Added an asset pipeline

- app/assets/stylesheets/lisa-app.scss
- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/_tabular-data.scss
- app/assets/stylesheets/partials/_variables.scss
- app/controllers/SummaryController.scala
- app/views/govuk_wrapper.scala.html
- app/views/registration/summary.scala.html
- test/controllers/SummaryControllerSpec.scala
Updated to have parity with design guidelines: https://www.gov.uk/service-manual/design/check-your-answers-pages
> LISA-1296: Amended check your answers page

- app/controllers/RosmController.scala
- app/views/error/access_denied.scala.html
- app/views/error/errorSummaryOrgTemplate.scala.html
- app/views/error_template.scala.html
- app/views/feedback/feedbackQuestionnaire.scala.html
- app/views/feedback/thanks.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/home/home.scala.html
- app/views/main_template.scala.html
- app/views/registration/application_pending.scala.html
- app/views/registration/application_rejected.scala.html
- app/views/registration/application_submitted.scala.html
- app/views/registration/application_successful.scala.html
- app/views/registration/business_structure.scala.html
- app/views/registration/matching_failed.scala.html
- app/views/registration/organisation_details.scala.html
- app/views/registration/summary.scala.html
- app/views/registration/trading_details.scala.html
- app/views/registration/your_details.scala.html
- test/controllers/RosmControllerSpec.scala
Now the user wont be redirected to the application sent page until the
caching process has completed.
Also: the views now have the copyright notices.
> LISA-1368: Updated RosmController and Spec

- app/controllers/ApplicationSubmittedController.scala
- app/controllers/RosmController.scala
- test/controllers/ApplicationSubmittedControllerSpec.scala
- test/controllers/RosmControllerSpec.scala
Application submitted email removed from success page and added into the submission process.
> LISA-1534: Submission email sent as part of submission action

- project/FrontendBuild.scala
- test/controllers/HomePageControllerSpec.scala
* Removed hmrctest dependency
* Updated any of the UnitSpec references to use PlaySpec
Also bumped authclient version by a minor release. All acceptance and unit tests continue to pass as before.
> LISA-1536: Removed reference to hmrctest

- conf/application.conf
The first page the user is taken to after logging into GG should be the company structure page
> Updated login callback url

- app/views/registration/application_submitted.scala.html
Added clarification that the 14 day review process is 14 calendar days, as per latest content review.
See also: https://github.com/hmrc/hmrc-email-renderer/pull/194
> LISA-1883: Updated application submitted page

- app/views/registration/summary.scala.html
- conf/application.conf
Had to amend legal notice on check your answers as the old styles had been deprecated.
> Updated assets frontend to latest 3.x version

- conf/messages
@Muhammad-Ali-Ahmad – I've removed primes from the messages file. At some point, I've been chatting with some of the devs, because I'd like a unit test that checks for primes in the messages file and this would throw up an error.
> DDCNLS-5590: Remove primes from messages file

- app/views/error/access_denied_assistant.scala.html
- app/views/error/access_denied_individual_or_agent.scala.html
- app/views/registration/application_pending.scala.html
- app/views/registration/application_rejected.scala.html
- app/views/registration/application_submitted.scala.html
- app/views/registration/application_successful.scala.html
- app/views/registration/business_structure.scala.html
- app/views/registration/matching_failed.scala.html
- app/views/registration/organisation_details.scala.html
- app/views/registration/summary.scala.html
- app/views/registration/trading_details.scala.html
- app/views/registration/your_details.scala.html
- conf/messages
makes page titles come from message file
> DDCNLS-5587

- .github/PULL_REQUEST_TEMPLATE.md
- build.sbt
- conf/messages
- project/AppDependencies.scala
- project/plugins.sbt
##Bug fix
added validation for isaRefProviderNumber
[performance Test](https://github.com/hmrc/lisa-performance-tests)
[acceptance Test](https://github.com/hmrc/lisa-api-tests)
> DDCE-265 content changed for hint message

- app/views/registration/application_rejected.scala.html
- conf/messages
- project/AppDependencies.scala
##New feature
- Content changes on Application Rejected page
> DDCE-486 Contet change on application reject

- app/views/registration/business_structure.scala.html
- conf/messages
- project/AppDependencies.scala
- test/controllers/BusinessStructureControllerSpec.scala
##New feature
- H1 changes for Select your company Structure page
- link to Acceptance Test PR - [https://github.com/hmrc/lisa-api-tests/pull/93](url)
> DDCE-504 Change in H1 on Select your company Stucture

- conf/messages
Updated Hint messages
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DDCE-506:hint messages updated

- conf/messages
##New feature)
Content change on /reviewing-your-application page paragraph 1
> DDCE-495 Content change on /reveiwing-your-application

- conf/messages
- test/controllers/TradingDetailsControllerSpec.scala
updated error messages
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DDCE-499:updated error messages

- app/assets/stylesheets/lisa-app.scss
##updated Cosmetic Feature - Background Color
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DDCE-487:updated BGV Color

- conf/messages
Added "(opens in a new window or tab)" to link on /application-successful
No changes to unit or acceptance tests required
Dependencies are up to date (apart from some major versions which could be breaking changes)
> DDCE-581: Content change on /application-successful

- app/services/AuthorisationService.scala
- app/views/registration/summary.scala.html
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/connectors/EmailConnectorSpec.scala
- test/connectors/RosmConnectorSpec.scala
- test/connectors/TaxEnrolmentConnectorSpec.scala
- test/connectors/TaxEnrolmentJsonFormatsSpec.scala
- test/controllers/RosmControllerSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/services/AuthorisationServiceSpec.scala
- test/services/RosmServiceSpec.scala
##Maintenance 
Content change to update button on /check-your-answers page. Also updated some minor dependencies/ plugins.
> [DDCE-645] update summary page button content

- app/models/YourDetails.scala
- conf/messages
- test/controllers/YourDetailsControllerSpec.scala
- test/models/YourDetailsSpec.scala
Updating error messages on /your-details
Added new unit test for validation failures
No dependency updates required as they have just been done
Link to acceptance test PR: https://github.com/hmrc/lisa-api-tests/pull/97
~~Email regex was not required to be implemented as we are using the "email" mapping in the form model (see [here](https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type%3Demail)) for more info)~~
Have implemented custom email regex similar to other services because the play default mapping for email allows things like "test@test" (missing domain) which we can't have
- Is there any still commented or unused code? Lingering …
> [DDCE-507] Updated error messages on /your-details

- app/views/registration/application_submitted.scala.html
- conf/messages
Content change on /application-submitted page.
> DDCE-641 Content changes on /application-submitted page

- app/models/OrganisationDetails.scala
- conf/messages
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/models/OrganisationDetailsSpec.scala
1. Updated Error message on Company Details page
2. Updated Unit test for the same
3. Link to Acceptance Test PR >> https://github.com/hmrc/lisa-api-tests/pull/99 
> DDCE-498 Update Error message on Company Details page

- app/config/frontendAppConfig.scala
- app/controllers/AccessibilityStatementController.scala
- app/views/accessibility_statement_view.scala.html
- app/views/govuk_wrapper.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/controllers/AccessibilityStatementControllerSpec.scala
##New feature
As per the requirement, have added Accessibility statement in Lisa frontend.
The dependent PRs are also created for Acceptance and app-config-base:
The app-config-base PR should be merged first and then the remaining PRs.
> DDCE-991 Added accessibility statement

- conf/application.conf
##New Feature
Updated firstPublished and lastUpdated dates in conf file as it should the date of deployment in Production. The other code has  already been deployed in master. 
> DDCE-991 Updated dates in conf file

- app/config/frontendAppConfig.scala
- app/views/accessibility_statement_view.scala.html
- conf/application.conf
- conf/messages
##New feature
Updated Accessibility statement as per the ticket.
Related PR in acceptance test, which should be merged first:
https://github.com/hmrc/lisa-api-tests/pull/102
> DDCE-1092 Modified content of lisa accessibility statement

- app/config/frontendAppConfig.scala
- app/controllers/ErrorController.scala
- app/controllers/LisaBaseController.scala
- conf/application.conf
- test/controllers/BusinessStructureControllerSpec.scala
- test/controllers/ErrorControllerSpec.scala
- test/controllers/LisaBaseControllerSpec.scala
> DDCE-1076: migrate to bas gateway

- app/views/registration/trading_details.scala.html
Added novalidate to reference number form to avoid HTML5 validation.
> [EH][DDCE-1226] Added novalidate to reference number form

- app/assets/stylesheets/lisa-app.scss
- app/views/govuk_wrapper.scala.html
Fix issue described in ticket [DDCE-1224](https://jira.tools.tax.service.gov.uk/browse/DDCE-1224)
I also updated the colour and thickness of the inputs to match GDS
> [DP][DDCE-1224] Fix menu toggle on small screen issue

- app/assets/stylesheets/lisa-app.scss
- app/assets/stylesheets/partials/_variables.scss
- app/views/govuk_wrapper.scala.html
- app/views/main_template.scala.html
- app/views/registration/organisation_details.scala.html
- app/views/registration/trading_details.scala.html
- app/views/registration/your_details.scala.html
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/TradingDetailsControllerSpec.scala
- test/controllers/YourDetailsControllerSpec.scala
Basically we had to replace the play-ui components that were causing the issues with our own html, so that's what most of this is.
The [ticket](https://jira.tools.tax.service.gov.uk/browse/DDCE-1237) had 6 parts to action:
1. Done
2. Was already fixed previously
3. This issue did not appear (it was already fixed I assume as it's controlled externally)
4. We can't do this without moving to new govuk-frontend
5. Done
6. We were using custom CSS for `form-field-error` so I updated that rather than switch to the other class (which was out of date anyway due to old assets). Other classes have been swapped as recommended
Also requires AT changes, link here: https://github.com/hmrc/lisa-api-tests/pull/109
> [DP][DDCE-1237] Multiple accessibility fixes

- conf/messages
Updated error message for accessibility.
https://github.com/hmrc/lisa-api-tests/pull/111
> [RS][DDCE-1229] Error message content update.

- app/views/govuk_wrapper.scala.html
- build.sbt
- project/AppDependencies.scala
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/TradingDetailsControllerSpec.scala
- test/controllers/YourDetailsControllerSpec.scala
Removed tracking consent helper as it was being brought in by hmrcHead and duplicated on the frontend.
> [DDCE-1752][SC] remove tracking constant helper

- build.sbt
> [DDCE-1752] scala version back to 2.12.12

- app/connectors/RosmConnector.scala
- app/models/OrganisationDetails.scala
- app/models/TradingDetails.scala
- app/models/YourDetails.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
Updated Bootstrap to 5.3.0 and uplifted all the dependencies.
> [RS][DDCE-1901] Bootstrap 5.3 update.

- .gitignore
- app/views/govuk_wrapper.scala.html
- project/AppDependencies.scala
Literally just removed a <main> and updated some dependencies.
> [RS][DDCE-1776] Removing duplicate main element.

- app/controllers/BusinessStructureController.scala
- app/controllers/ErrorController.scala
- app/controllers/HomePageController.scala
- app/controllers/LisaBaseController.scala
- app/controllers/MatchingFailedController.scala
- app/controllers/OrganisationDetailsController.scala
- app/controllers/ReapplyController.scala
- app/controllers/RosmController.scala
- app/controllers/TradingDetailsController.scala
- app/controllers/YourDetailsController.scala
- app/views/error_template.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/page_not_found_template.scala.html
- app/views/registration/application_rejected.scala.html
- app/views/registration/matching_failed.scala.html
- build.sbt
- conf/prod.routes
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/BusinessStructureControllerSpec.scala
- test/controllers/LisaBaseControllerSpec.scala
- test/controllers/OrganisationDetailsControllerSpec.scala
- test/controllers/ReapplyControllerSpec.scala
- test/controllers/RosmControllerSpec.scala
- test/controllers/SummaryControllerSpec.scala
- test/controllers/TradingDetailsControllerSpec.scala
- test/controllers/YourDetailsControllerSpec.scala
> DDCE-2028: Play 2.8 Upgrade

- app/views/registration/application_successful.scala.html
- app/views/registration/matching_failed.scala.html
- conf/app.routes
- conf/messages
- project/AppDependencies.scala
> DDCE-2342: Reverse tabnapping fix

- app/assets/stylesheets/lisa-app.scss
- app/config/AppConfig.scala
- app/controllers/SignOutController.scala
- app/views/govuk_wrapper.scala.html
- app/views/registration/application_submitted.scala.html
- app/views/registration/summary.scala.html
- app/views/registration/trading_details.scala.html
- app/views/timeout_sign_out.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- project/AppDependencies.scala
- test/controllers/SignOutControllerSpec.scala
Accessibility issues identified can be found here: https://github.com/hmrc/accessibility-audits-live/issues/388
Issues addressed:
- Error summary links (A)
- No space between attributes (A)
- No timeout dialogue (A): **Added additional service page to callback when user timeout**
- Text is clipped (AA)
> [EH][DDCE-2340] Fixed A and AA accessibility issues

- app/views/govuk_wrapper.scala.html
- Small change to fix timeout behaviour
> [EH][DDCE-2340] Added missing timeoutUrl

- .gitignore
- README.md
- project/AppDependencies.scala
- project/plugins.sbt
- scalastyle-config.xml
Looks to be a http-caching-client Bobby rule violation: https://catalogue.tax.service.gov.uk/service/lisa-frontend
I think we are still able to merge and deploy even with this warning/error: https://hmrcdigital.slack.com/archives/C010R52J220/p1691498818533099
> DDCE-4528 Update readme + dependencies
